In [1]:
import random
import numpy as np
import pandas as pd

#import viz # curriculum example visualizations

np.random.seed(29)

### 1. How likely is it that you roll doubles when rolling two dice?

In [2]:
#running simmulation 10k 

die1 = np.random.choice ([1,2,3,4,5,6], 10_000)
die2 = np.random.choice ([1,2,3,4,5,6], 10_000)
samesies = die1 == die2

samesies.mean()

0.1613

In [3]:
#jons
nrows= 100_000
ncols = 2

In [4]:
rolls = np.random.choice ([1,2,3,4,5,6], nrows * ncols).reshape (nrows, ncols)
rolls

array([[3, 3],
       [3, 3],
       [2, 1],
       ...,
       [6, 1],
       [6, 2],
       [3, 1]])

In [5]:
df = pd.DataFrame(rolls)
df.head()

0  1
0  3  3
1  3  3
2  2  1
3  4  1
4  4  4

In [6]:
df.apply(lambda row: row.values[0] == row.values[1], axis=1)

0         True
1         True
2        False
3        False
4         True
         ...  
99995    False
99996    False
99997    False
99998    False
99999    False
Length: 100000, dtype: bool

In [7]:
df.apply(lambda row: row.values[0] == row.values[1], axis=1).mean()

0.16622

### 2. If you flip 8 coins, what is the probability of getting exactly 3 heads? What is the probability of getting more than 3 heads?

In [8]:
#flip 8 coins - options heads or tails
#1 = Heads, 0=Tails

outcomes = [1, 0]
n_simulation = 10_000
n_trials = 8

flip = np.random.choice(outcomes, size = (n_simulation, n_trials))



In [9]:
results = flip.sum(axis=1)

In [10]:
(results == 3).mean()

0.2179

In [11]:
n_trials = 10_000
n_coins = 8

flips = np.random.choice([True, False], size=(n_trials, n_coins))
flips

array([[ True,  True, False, ...,  True, False,  True],
       [ True, False,  True, ...,  True, False, False],
       [ True,  True, False, ...,  True,  True, False],
       ...,
       [ True,  True, False, ..., False, False, False],
       [ True,  True,  True, ..., False,  True,  True],
       [ True,  True, False, ...,  True, False,  True]])

In [12]:
df = pd.DataFrame(flips)
df.head()

0      1      2      3      4      5      6      7
0   True   True  False   True  False   True  False   True
1   True  False   True  False   True   True  False  False
2   True   True  False   True  False   True   True  False
3  False  False  False   True   True  False  False  False
4   True  False   True  False  False   True  False   True

In [13]:
df['head_count'] = df.sum(axis=1)
df['three_heads'] = df.head_count == 3
df

0      1      2      3      4      5      6      7  head_count  \
0      True   True  False   True  False   True  False   True           5   
1      True  False   True  False   True   True  False  False           4   
2      True   True  False   True  False   True   True  False           5   
3     False  False  False   True   True  False  False  False           2   
4      True  False   True  False  False   True  False   True           4   
...     ...    ...    ...    ...    ...    ...    ...    ...         ...   
9995   True  False   True  False  False   True   True   True           5   
9996   True  False  False  False  False   True  False  False           2   
9997   True   True  False   True   True  False  False  False           4   
9998   True   True   True   True  False  False   True   True           6   
9999   True   True  False   True   True   True  False   True           6   

      three_heads  
0           False  
1           False  
2           False  
3           False  
4           False  
...           ...  
9995        False  
9996        False  
9997        False  
9998        False  
9999        False  

[10000 rows x 10 columns]

In [14]:
df.three_heads.mean()

0.2126

In [15]:
df['more_than_three'] = df.head_count >= 3
df.more_than_three.mean()

0.8517

### 3. There are approximitely 3 web development cohorts for every 1 data science cohort at Codeup. Assuming that Codeup randomly selects an alumni to put on a billboard, what are the odds that the two billboards I drive past both have data science students on them?

In [16]:
#   1 = DS & 0 = WD, trials =2 for billboards

outcomes = [1, 0]
n_simulation = 10_000
n_trials = 2

billboards = np.random.choice(outcomes, size=(n_simulation, n_trials), p = [0.25, 0.75])
billboards

array([[0, 0],
       [0, 0],
       [0, 0],
       ...,
       [0, 1],
       [0, 0],
       [0, 0]])

In [17]:
results = billboards.sum(axis=1)
results

array([0, 0, 0, ..., 1, 0, 0])

In [18]:
(results == 2).mean()

0.0632

In [19]:
n_trials=2
n_simulation = 10_000

billboard = np.random.choice(["DS","WD","WD","WD"], size = (n_simulation, n_trials))
billboard

array([['WD', 'WD'],
       ['WD', 'DS'],
       ['WD', 'WD'],
       ...,
       ['WD', 'WD'],
       ['WD', 'WD'],
       ['WD', 'WD']], dtype='<U2')

In [20]:
df = pd.DataFrame(billboard)
df.head()

0   1
0  WD  WD
1  WD  DS
2  WD  WD
3  WD  WD
4  WD  WD

In [21]:
df['both_ds'] = (df[0] == "DS") & (df[1] == "DS")
df.both_ds.mean()

0.0661

### 4. Codeup students buy, on average, 3 poptart packages with a standard deviation of 1.5 a day from the snack vending machine. If on monday the machine is restocked with 17 poptart packages, how likely is it that I will be able to buy some poptarts on Friday afternoon? (Remember, if you have mean and standard deviation, use the np.random.normal)

In [22]:
#3 poptarts w/ std 1.5 
#monday = 17 how likely to be out by friday

In [23]:
n_simulations = 10_000
n_trials = 5 #5 days

In [24]:
poptarts = np.random.normal(3, 1.5, n_simulations * n_trials).astype(int).reshape(n_simulations, n_trials)
#poptarts.astype(int)
poptarts

array([[2, 1, 3, 1, 5],
       [3, 2, 1, 2, 1],
       [2, 0, 0, 2, 4],
       ...,
       [2, 2, 1, 4, 3],
       [3, 1, 0, 3, 1],
       [2, 2, 2, 0, 2]])

In [25]:
poptarts = pd.DataFrame(poptarts)
poptarts.round()

0  1  2  3  4
0     2  1  3  1  5
1     3  2  1  2  1
2     2  0  0  2  4
3     3  1  2  2  1
4     2  5  4  1  3
...  .. .. .. .. ..
9995  0  3  4  4  3
9996  4  4  4  1  0
9997  2  2  1  4  3
9998  3  1  0  3  1
9999  2  2  2  0  2

[10000 rows x 5 columns]

In [26]:
poptarts_friday = poptarts.sum(axis=1)<17
poptarts_friday.mean()

0.8774

In [27]:
n_simulations = 10_000
n_trials = 5

In [28]:
poptarts= np.random.normal(3, 1.5, n_simulations * n_trials).astype(int).reshape(n_simulations, n_trials)
df = pd.DataFrame(poptarts)
df.head()

0  1  2  3  4
0  1  4  1  5  3
1  2  3  1  1  2
2  2  2  0  5  0
3  3  3  2  1  3
4  3  5  2  3  1

In [29]:
df['poptarts_bought'] = df.sum(axis=1)
df

0  1  2  3  4  poptarts_bought
0     1  4  1  5  3               14
1     2  3  1  1  2                9
2     2  2  0  5  0                9
3     3  3  2  1  3               12
4     3  5  2  3  1               14
...  .. .. .. .. ..              ...
9995  1  3  0  1  3                8
9996  4  6  4  3  3               20
9997  2  2  4  2  3               13
9998  4  2  5  2  2               15
9999  4  2  1  2  5               14

[10000 rows x 6 columns]

In [30]:
df["poptarts_remain"] = df["poptarts_bought"] > 17
df["poptarts_remain"].mean()

0.0706

### 5. Compare Heights

- Men have an average height of 178 cm and standard deviation of 8cm.
- Women have a mean of 170, sd = 6cm.
- Since you have means and standard deviations, you can use np.random.normal to generate observations.
- If a man and woman are chosen at random, P(woman taller than man)?

In [31]:
n_simulations = 10_000
men = np.random.normal(178, 8, size=n_simulations)
women = np.random.normal(170, 6, size=n_simulations)

In [32]:
(women > men).mean()

0.2133

In [33]:
#df = pd.DataFrame({'male_heights'})

### 6. When installing anaconda on a student's computer, there's a 1 in 250 chance that the download is corrupted and the installation fails. What are the odds that after having 50 students download anaconda, no one has an installation issue? 100 students?

- What is the probability that we observe an installation issue within the first 150 students that download anaconda?

- How likely is it that 450 students all download anaconda without an issue?



In [34]:
1/250

0.004

In [35]:
1-(1/250)

0.996

In [36]:
outcomes = [0,1]
n_simulations = 10_000
n_trials = 50

fails = np.random.choice(outcomes, size=(n_simulations, n_trials), p=[.996,.004])
fails = fails.sum(axis=1)
fails = (fails >=1).mean()
1 - fails

0.8193

In [37]:
outcomes = [0,1]
n_simulations = 100_000
n_trials = 100

fails = np.random.choice(outcomes, size=(n_simulations, n_trials), p=[.996,.004])
fails = fails.sum(axis=1)
1 - (fails >=1).mean()


0.66947

In [38]:
outcomes = [0,1]
n_simulations = 100_000
n_trials = 150

fails = np.random.choice(outcomes, size=(n_simulations, n_trials), p=[.996,.004])
fails = fails.sum(axis=1)
1 - (fails >=1).mean()

0.54747

In [39]:
outcomes = [0,1]
n_simulations = 100_000
n_trials = 450

fails = np.random.choice(outcomes, size=(n_simulations, n_trials), p=[.996,.004])
fails = fails.sum(axis=1)
1 - (fails >=1).mean()

0.16510000000000002

### 7. There's a 70% chance on any given day that there will be at least one food truck at Travis Park. However, you haven't seen a food truck there in 3 days. How unlikely is this?

In [40]:
outcome = [1,0]
n_simulations = 100_000
n_trials = 3

food_truck = np.random.choice(outcome, size =(n_simulations, n_trials), p=[.7,.3])
food_truck = food_truck.sum(axis=1)
#sum chances in each row
#mean if sum ==0


In [41]:
print(f"The chance of not seeing a food truck in 3 days is {(food_truck == 0).mean()}")

The chance of not seeing a food truck in 3 days is 0.02634


### 7b. How likely is it that a food truck will show up sometime this week?


In [42]:
outcome = [1,0]
n_simulations = 100_000
n_trials = 7

food_truck = np.random.choice(outcome, size =(n_simulations, n_trials), p=[.7,.3])
food_truck = food_truck.sum(axis=1)

In [43]:
print(f"The chance of not seeing a food truck in 7 days is {(food_truck == 0).mean()}")

The chance of not seeing a food truck in 7 days is 0.00014


### 8. If 23 people are in the same room, what are the odds that two of them share a birthday? What if it's 20 people? 40?

In [44]:
#range of 1:365
outcomes = list(range(1,366))
n_simulations = 10_000
n_trials = 23

same_birthday = np.random.choice(outcomes, size=(n_simulations, n_trials))
same_birthday = pd.DataFrame(same_birthday)
same_birthday.head()


0    1    2    3    4    5    6    7    8    9   ...   13   14   15   16  \
0   97  272   90  223  118  121    3   72   46  171  ...  109  233  305  322   
1   40    7   51   77  139  149  171   63   10   63  ...   77  285   21  257   
2  227  284   94  360    8  273  339  146  244   54  ...  250  270  362  353   
3  108  263  160   18  349   61   47  284  319  260  ...   47  161  206  260   
4  213   77   42  363  257   59  242  183  144  307  ...   22   70  180  334   

    17   18   19   20   21   22  
0  210   99   20  148  194   27  
1   59  142   50   39  340  339  
2  212  208  189  330   21   17  
3  235  325   78  281   98  190  
4   85   68   66   47    6  215  

[5 rows x 23 columns]

In [45]:
#nunique will count the numbers that are unique in the dataset so if it is under the target amount then it should pass true

same_birthday['matching_birthdays'] = same_birthday.nunique(axis = 1) < n_trials
same_birthday

0    1    2    3    4    5    6    7    8    9  ...   14   15   16  \
0      97  272   90  223  118  121    3   72   46  171  ...  233  305  322   
1      40    7   51   77  139  149  171   63   10   63  ...  285   21  257   
2     227  284   94  360    8  273  339  146  244   54  ...  270  362  353   
3     108  263  160   18  349   61   47  284  319  260  ...  161  206  260   
4     213   77   42  363  257   59  242  183  144  307  ...   70  180  334   
...   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...   
9995    5  103  315   25  165   98   43  230  185  318  ...  143   41    1   
9996  342  260  257  185   76  200   19  129  232   47  ...  222  111   16   
9997   27  358  121  213    3   33  359  138  159  258  ...  344  147  111   
9998  220  353  247  353  240  273  245  278  239  293  ...  202  174  201   
9999  208  287  102   10   36   12  264   84  267  199  ...  114  286  184   

       17   18   19   20   21   22  matching_birthdays  
0     210   99   20  148  194   27               False  
1      59  142   50   39  340  339                True  
2     212  208  189  330   21   17               False  
3     235  325   78  281   98  190                True  
4      85   68   66   47    6  215               False  
...   ...  ...  ...  ...  ...  ...                 ...  
9995  175  201  291  170  110  103                True  
9996  262  213  239  291  198   54                True  
9997  170   21   69  346   35  125               False  
9998  312   86  265  274   91   39                True  
9999  328   65  302  107  260  283               False  

[10000 rows x 24 columns]

In [46]:
two_bdays = same_birthday['matching_birthdays'].mean()
two_bdays

0.5095

In [47]:
print(f"The odds of 23 people sharing a birthday are {two_bdays}")

The odds of 23 people sharing a birthday are 0.5095


### JON'S CODE:

In [49]:
def shared_birthday(people):

    nrows = 100_000 # set rows to number of simulations
    ncols = people  # set columns to number of people in each simulation

    # create array with each value representing the numbered day of the year that person was born on. (This ignores leap years)
    # reshape the aray into trial groups
    sightings = np.random.choice([r for r in range(366)], nrows * ncols).reshape(nrows, ncols)

    # convert to data frame
    df = pd.DataFrame(sightings)

    # Add boolian column to df showing weather there are less unique numbers in each row (trial) than there are total columns
    df['matching_birthdays'] = df.nunique(axis=1) < ncols

    # get mean of calculation True/False columns
    # format and print results
    matching_birthdays = df['matching_birthdays'].mean()

    # print result
    print(f'The odds of a room of {ncols} people having at least two people that share a birthday are {round(matching_birthdays*100)}%')

In [51]:
num_list = [23, 20, 40]

for num in num_list:
    shared_birthday(num)

The odds of a room of 23 people having at least two people that share a birthday are 51%
The odds of a room of 20 people having at least two people that share a birthday are 41%
The odds of a room of 40 people having at least two people that share a birthday are 89%


### Mage Duel!
Let's use what we've learned to play a mage duel!

Imagine your wizard has 6d4 health points and you have spells that do 6d4 damage. "6d4" means rolling six 4-sided dice and summing the result.

Your opposing mage has 4d6 health points and spells that do 4d6. "4d6" means rolling four six-sided dice and summing the result.

Exercises
Simulate mage duels to answer who is the more powerful mage?

Before running simulations, do you have a hypothesis of which mage will win? Do you have a hunch? Write it down. This is your first exercise.
Simulate 10 mage duels. Is there a clear winner? Run that 10 duel simulation again. Was the answer similar?
Do the results change much at 100 duels?
Now, simulate 10,000 mage duels. Is there a clear winner?

In [89]:
#Wizard 1 
outcomes = [1,2,3,4]
n_simulations = 100
n_trials = 6


wizard_1 = np.random.choice(outcomes, size=(n_simulations, n_trials))
wizard_1 = pd.DataFrame(wizard_1)
wizard_1 = wizard_1.sum(axis=1)
wizard_1

0     18
1     11
2     17
3     21
4     13
      ..
95    19
96    17
97    17
98    16
99    11
Length: 100, dtype: int64

In [90]:
#wizard 2
#Wizard 1 
outcomes = [1,2,3,4,5,6]
n_simulations = 100
n_trials = 4


wizard_2 = np.random.choice(outcomes, size=(n_simulations, n_trials))
wizard_2 = pd.DataFrame(wizard_2)
wizard_2 = wizard_2.sum(axis=1)
wizard_2


0      7
1     10
2      9
3     21
4      8
      ..
95    11
96    19
97    15
98    15
99     9
Length: 100, dtype: int64

In [91]:
duel = pd.concat([wizard_1,wizard_2],axis=1)
duel

0   1
0   18   7
1   11  10
2   17   9
3   21  21
4   13   8
..  ..  ..
95  19  11
96  17  19
97  17  15
98  16  15
99  11   9

[100 rows x 2 columns]

In [92]:
duel = duel.rename(columns={0: "Wizard1", 1:"Wizard2"})
duel

Wizard1  Wizard2
0        18        7
1        11       10
2        17        9
3        21       21
4        13        8
..      ...      ...
95       19       11
96       17       19
97       17       15
98       16       15
99       11        9

[100 rows x 2 columns]

In [93]:
winner = duel.Wizard1 > duel.Wizard2
winner.mean()

#percent that Wizard 1 wins

0.57

In [94]:
1-winner.mean()

#percent that Wizard 2 wins

0.43000000000000005

At 10 duels the probability is 70/30
At 100 duels the probability is 57/43
At 10,000 duels the probability is 54/45

In [ ]:
#will try to attempt last bonus later